[ui]
diff-formatter = "delta"

[merge-tools]
delta.diff-expected-exit-codes = [0, 1]

[user]
name = "reVrost"
email = "revrost@gmail.com"

[aliases]
tug = ["bookmark", "set", "main", "--to", "@"]
pm = ["bookmark", "set", "main", "-r", "@", "&&", "git", "push"]
